services:
  taskmanagementapi:
    build:
      context: .
      dockerfile: TaskManagement.API/Dockerfile
    container_name: taskmanagementapi_v2
    ports:
      - "5120:8080"
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://mendozaselwys:25kmYrKwNis7kh9c@cluster0.ek0fd.mongodb.net/
      - DATABASE_NAME=TaskManagementDB
      - AUTH0_DOMAIN=dev-pyk3xhommtrhi3du.us.auth0.com
      - AUTH0_CLIENT_ID=oQvCWrQizcg4TVvGZE5rASK79kJbT2YS
      - AUTH0_CLIENT_SECRET=g62oEW50aBo28WOexB5FW7hgOpu7jAdGaDMHYqDsCY9UwySH67Fq0bNowUfSmtLm
      - AUTH0_AUDIENCE=https://dev-pyk3xhommtrhi3du.us.auth0.com/api/v2/